### ISSUE TITLE
400 Bad Request: malformed Host header for /v2/catalog

### ISSUE THREAD

**Issue by srinat999** [cloudfoundry-community/cf-containers-broker#58]
I tried running the broker as a docker container from the docker image available at frodenas/cf-containers-broker.

I ran the image using the command:

```
sudo docker run -d --name cf-containers-broker --publish 80:80 --volume /var/run:/var/run --volume /home/ubuntu/docker/cf-containers-broker/config:/config --volume /home/ubuntu/docker/cf-containers-broker/log:/app/log  frodenas/cf-containers-broker
```

However, I get this error while trying to query /v2/catalog.

```
Docker::Error::ClientError in V2::CatalogsController#show
400 Bad Request: malformed Host header
```

Here are the app logs:

```
Started GET "/v2/catalog" for 10.0.0.14 at 2016-09-22 09:45:16 +0000
Processing by V2::CatalogsController#show as JSON
  Request: {"headers":{"REMOTE_ADDR":"10.0.0.14","REQUEST_METHOD":"GET","REQUEST_PATH":"/v2/catalog","PATH_INFO":"/v2/catalog","REQUEST_URI":"/v2/catalog","SERVER_PROTOCOL":"HTTP/1.1","HTTP_VERSION":"HTTP/1.1","HTTP_X_BROKER_API_VERSION":"2.10","HTTP_X_VCAP_REQUEST_ID":"dc45b8a1-298d-4aff-6c90-0d90723c2e1d::d6a35a9d-d776-4f05-ab9f-6b48432c391a","HTTP_ACCEPT":"application/json","HTTP_AUTHORIZATION":"[PRIVATE DATA HIDDEN]","HTTP_USER_AGENT":"HTTPClient/1.0 (2.7.1, ruby 2.3.1 (2016-04-26))","HTTP_HOST":"10.0.0.114","SERVER_NAME":"10.0.0.114","SERVER_PORT":"80","QUERY_STRING":"","SCRIPT_NAME":"","SERVER_SOFTWARE":"Unicorn 5.0.0"},"body":""}
Completed 500 Internal Server Error in 7ms

Docker::Error::ClientError (400 Bad Request: malformed Host header):
  app/models/docker_manager.rb:249:in `validate_docker_remote_api'
  app/models/docker_manager.rb:20:in `initialize'
  app/models/plan.rb:66:in `new'
  app/models/plan.rb:66:in `build_container_manager'
  app/models/plan.rb:26:in `initialize'
  app/models/plan.rb:11:in `new'
  app/models/plan.rb:11:in `build'
  app/models/service.rb:11:in `block in build'
  app/models/service.rb:11:in `map'
  app/models/service.rb:11:in `build'
  app/models/catalog.rb:13:in `block in services'
  app/models/catalog.rb:13:in `map'
  app/models/catalog.rb:13:in `services'
  app/controllers/v2/catalogs_controller.rb:5:in `show'


  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_source.erb (5.5ms)
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.1ms)
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.7ms)
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (15.2ms)
```

Any help is appreciated.

**Comment by drnic** [comment]
I was playing with the docker image today and experienced the same issue.
